// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdxOKf-a5SQari3skmTToGamyyUkeLJfs',
    appId: '1:717960598789:web:03a88fc436370044a1936c',
    messagingSenderId: '717960598789',
    projectId: 'fir-divedeep',
    authDomain: 'fir-divedeep.firebaseapp.com',
    storageBucket: 'fir-divedeep.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBatTgOwqQ1kfRAFSLVLc_VfYriXscUbIE',
    appId: '1:717960598789:android:55053663c418b1c6a1936c',
    messagingSenderId: '717960598789',
    projectId: 'fir-divedeep',
    storageBucket: 'fir-divedeep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoxu9IjAVk1xAG-SgPhWrCdFyxamH9MTM',
    appId: '1:717960598789:ios:0b68188349510444a1936c',
    messagingSenderId: '717960598789',
    projectId: 'fir-divedeep',
    storageBucket: 'fir-divedeep.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoxu9IjAVk1xAG-SgPhWrCdFyxamH9MTM',
    appId: '1:717960598789:ios:0b68188349510444a1936c',
    messagingSenderId: '717960598789',
    projectId: 'fir-divedeep',
    storageBucket: 'fir-divedeep.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
